

# set the database properties
db.host=mariadb
db.user=metuser
db.password=123
db.managementSystem=mariadb

cache.val=true
cache.stat=true

rscript.bin=
redirect=metviewer

folders.plot_xml=/opt/tomcat/webapps/metviewer_output//xml
folders.r_tmpl=/opt/tomcat/webapps/metviewer//R_tmpl
folders.r_work=/opt/tomcat/webapps/metviewer//R_work
folders.plots=/opt/tomcat/webapps/metviewer_output//plots
folders.data=/opt/tomcat/webapps/metviewer_output//data
folders.scripts=/opt/tomcat/webapps/metviewer_output//scripts
url.output=http://localhost:8080/metviewer_output/

log.file=
python.env=/usr/local/
metcalcpy.home=/METviewer-python/METcalcpy/
metplotpy.home=/METviewer-python/METplotpy/metplotpy/
