[config]

PROCESS_LIST = PointStat

LOOP_BY = INIT

INIT_TIME_FMT = %Y%m%d%H
INIT_BEG = 2026011503
INIT_END = 2026011503
INIT_INCREMENT = 24H

## Time: 0..51
LEAD_SEQ = 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51

POINT_STAT_CONFIG_FILE = /work/config/met/PointStatConfig_wrfdiag_metplus

MODEL = WRFDIAG

FCST_POINT_STAT_INPUT_DIR = /work/input/wrf_diag
FCST_POINT_STAT_INPUT_TEMPLATE = wrfdiag_d01_{init?fmt=%Y-%m-%d_%H}.nc

OBS_POINT_STAT_INPUT_DIR = /work/input/obs_nc
OBS_POINT_STAT_INPUT_TEMPLATE = imgw_synop.nc

POINT_STAT_OUTPUT_DIR = /work/output/point_stat/metplus_surface_test

POINT_STAT_FCST_FILE_TYPE = NETCDF_NCCF

POINT_STAT_MESSAGE_TYPE = ADPSFC

POINT_STAT_MASK_GRID = FULL
POINT_STAT_MASK_POLY =
POINT_STAT_MASK_SID =

OBS_POINT_STAT_WINDOW_BEGIN = 0
OBS_POINT_STAT_WINDOW_END = 0

POINT_STAT_INTERP_FIELD = BOTH
POINT_STAT_INTERP_VLD_THRESH = 1.0
POINT_STAT_INTERP_SHAPE = SQUARE
POINT_STAT_INTERP_METHOD = NEAREST
POINT_STAT_INTERP_WIDTH = 1

POINT_STAT_OUTPUT_FLAG_CNT = BOTH
POINT_STAT_OUTPUT_FLAG_SL1L2 = BOTH
POINT_STAT_OUTPUT_FLAG_MPR = BOTH

FCST_VAR1_NAME = T2
FCST_VAR1_LEVELS = ({lead?fmt=%H},*,*)
FCST_VAR1_THRESH = NA
OBS_VAR1_NAME = T2
OBS_VAR1_LEVELS = Z2
OBS_VAR1_THRESH = NA

FCST_VAR2_NAME = PSFC_HPA
FCST_VAR2_LEVELS = ({lead?fmt=%H},*,*)
FCST_VAR2_THRESH = NA
OBS_VAR2_NAME = PSFC_HPA
OBS_VAR2_LEVELS = Z0
OBS_VAR2_THRESH = NA

FCST_VAR3_NAME = WSPD10
FCST_VAR3_LEVELS = ({lead?fmt=%H},*,*)
FCST_VAR3_THRESH = NA
OBS_VAR3_NAME = WSPD10
OBS_VAR3_LEVELS = Z10
OBS_VAR3_THRESH = NA

FCST_VAR4_NAME = WDIR10
FCST_VAR4_LEVELS = ({lead?fmt=%H},*,*)
FCST_VAR4_THRESH = NA
OBS_VAR4_NAME = WDIR10
OBS_VAR4_LEVELS = Z10
OBS_VAR4_THRESH = NA

FCST_VAR5_NAME = RH2
FCST_VAR5_LEVELS = ({lead?fmt=%H},*,*)
FCST_VAR5_THRESH = NA
OBS_VAR5_NAME = RH2
OBS_VAR5_LEVELS = Z2
OBS_VAR5_THRESH = NA

FCST_VAR6_NAME = TD2
FCST_VAR6_LEVELS = ({lead?fmt=%H},*,*)
FCST_VAR6_THRESH = NA
OBS_VAR6_NAME = TD2
OBS_VAR6_LEVELS = Z2
OBS_VAR6_THRESH = NA

FCST_VAR7_NAME = SLP
FCST_VAR7_LEVELS = ({lead?fmt=%H},*,*)
FCST_VAR7_THRESH = NA
OBS_VAR7_NAME = SLP
OBS_VAR7_LEVELS = Z0
OBS_VAR7_THRESH = NA