[config]

PROCESS_LIST = PointStat

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_INCREMENT = 24H

LEAD_SEQ = begin_end_incr(0, 51, 1)

POINT_STAT_CONFIG_FILE = /work/config/met/PointStatConfig_wrfdiag_metplus

FCST_POINT_STAT_INPUT_DIR = /work/input/wrfdiag
FCST_POINT_STAT_INPUT_TEMPLATE = wrfdiag_d01_{init?fmt=%Y-%m-%d_%H}.nc

OBS_POINT_STAT_INPUT_DIR = /work/input/obs_nc
OBS_POINT_STAT_INPUT_TEMPLATE = imgw_synop_{valid?fmt=%Y%m}.nc

POINT_STAT_OUTPUT_DIR = /work/output/point_stat/metplus_surface

POINT_STAT_FCST_FILE_TYPE = NETCDF_NCCF

FCST_VAR1_NAME = T2
FCST_VAR1_LEVELS = ({lead?fmt=%H},*,*)
OBS_VAR1_NAME = T2
OBS_VAR1_LEVELS = Z2

FCST_VAR2_NAME = PSFC
FCST_VAR2_LEVELS = ({lead?fmt=%H},*,*)
OBS_VAR2_NAME = PSFC
OBS_VAR2_LEVELS = Z0

FCST_VAR3_NAME = WSPD10
FCST_VAR3_LEVELS = ({lead?fmt=%H},*,*)
OBS_VAR3_NAME = WSPD10
OBS_VAR3_LEVELS = Z10

# FCST_VAR4_NAME = WDIR10
# FCST_VAR4_LEVELS = ({lead?fmt=%H},*,*)
# OBS_VAR4_NAME = WDIR10
# OBS_VAR4_LEVELS = Z10

FCST_VAR5_NAME = RH2
FCST_VAR5_LEVELS = ({lead?fmt=%H},*,*)
OBS_VAR5_NAME = RH2
OBS_VAR5_LEVELS = Z2

FCST_VAR6_NAME = TD2
FCST_VAR6_LEVELS = ({lead?fmt=%H},*,*)
OBS_VAR6_NAME = TD2
OBS_VAR6_LEVELS = Z2

FCST_VAR7_NAME = SLP
FCST_VAR7_LEVELS = ({lead?fmt=%H},*,*)
OBS_VAR7_NAME = SLP
OBS_VAR7_LEVELS = Z0
