alpha: 0.05
box_avg: 'False'
box_boxwex: 0.2
box_notch: 'False'
box_outline: 'True'
box_pts: 'False'

caption_align: 0.0
caption_col: '#FFFFFF'
caption_offset: 3.0
caption_size: 0.8
caption_weight: 1

cex: 1

colors:
- '#ff0000'

con_series:
- 1

create_html: 'False'

derived_series_1: []
derived_series_2: []

dump_points_1: 'False'
dump_points_2: 'False'

event_equal: 'False'

fcst_var_val_1:
  T2:
  - !ENV ${PLOTTING_STAT}

fcst_var_val_2: {}

grid_col: '#cccccc'
grid_lty: 3
grid_lwd: 1
grid_on: 'True'
grid_x: listX

indy_label:
- '09-10 06'
- '09-10 07'
- '09-10 08'
- '09-10 09'
- '09-10 10'
- '09-10 11'
- '09-10 12'
- '09-10 13'
- '09-10 14'
- '09-10 15'
- '09-10 16'
- '09-10 17'
- '09-10 18'
- '09-10 19'
- '09-10 20'
- '09-10 21'
- '09-10 22'
- '09-10 23'
- '09-11 00'
- '09-11 01'
- '09-11 02'
- '09-11 03'
- '09-11 04'
- '09-11 05'

indy_stagger_1: 'True'
indy_stagger_2: 'False'

indy_vals:
- '2025-09-10 06:00:00'
- '2025-09-10 07:00:00'
- '2025-09-10 08:00:00'
- '2025-09-10 09:00:00'
- '2025-09-10 10:00:00'
- '2025-09-10 11:00:00'
- '2025-09-10 12:00:00'
- '2025-09-10 13:00:00'
- '2025-09-10 14:00:00'
- '2025-09-10 15:00:00'
- '2025-09-10 16:00:00'
- '2025-09-10 17:00:00'
- '2025-09-10 18:00:00'
- '2025-09-10 19:00:00'
- '2025-09-10 20:00:00'
- '2025-09-10 21:00:00'
- '2025-09-10 22:00:00'
- '2025-09-10 23:00:00'
- '2025-09-11 00:00:00'
- '2025-09-11 01:00:00'
- '2025-09-11 02:00:00'
- '2025-09-11 03:00:00'
- '2025-09-11 04:00:00'
- '2025-09-11 05:00:00'

indy_var: fcst_valid_beg

legend_box: o
legend_inset:
  x: 0.0
  y: -0.25
legend_ncol: 1
legend_size: 0.8

line_type: None

list_stat_1:
- !ENV ${PLOTTING_STAT}

list_stat_2: []

list_static_val:
  fcst_var: T2

mar:
- 8
- 4
- 5
- 4

method: bca

mgp:
- 1
- 1
- 0

num_iterations: 1
num_threads: -1

plot_caption: Caption

plot_ci:
- std

plot_disp:
- 'True'

plot_filename: !ENV '${PLOTTING_CNT_OUTPUT_FILENAME}_${PLOTTING_STAT}.png'

plot_height: 8.5
plot_res: 72
plot_stat: median
plot_type: png16m
plot_units: in
plot_width: 11.0

points_path: !ENV '${PLOTTING_CNT_OUTPUT_DIR}'

random_seed: null

series_line_style:
- '-'

series_line_width:
- 2

series_order:
- 1

series_symbols:
- .

series_type:
- b

series_val_1:
  model:
  - WRF

series_val_2: {}

show_nstats: 'False'

show_signif:
- 'False'

stat_input: !ENV '${PLOTTING_CNT_STAT_INPUT}'

sync_yaxes: 'True'

title: !ENV 'WRF ${PLOTTING_STAT_LONG} for ${PLOTTING_CNT_LONG_VAR} by valid time'

title_align: 0.5
title_offset: -2
title_size: 1.5
title_weight: 2.0

user_legend:
- WRF

variance_inflation_factor: 'False'

vert_plot: 'False'

x2lab_align: 0.5
x2lab_offset: -0.5
x2lab_size: 0.8
x2lab_weight: 1
x2tlab_horiz: 0.5
x2tlab_orient: 1
x2tlab_perp: 1
x2tlab_size: 0.8

xaxis: Valid Time UTC
xaxis_reverse: 'False'

xlab_align: 0.5
xlab_offset: 2
xlab_size: 1
xlab_weight: 1

xlim: []

xtlab_decim: 0
xtlab_horiz: 0.5
xtlab_orient: 2
xtlab_perp: -0.75
xtlab_size: 0.8

y2lab_align: 0.5
y2lab_offset: 1
y2lab_size: 1
y2lab_weight: 1
y2lim: []
y2tlab_horiz: 0.5
y2tlab_orient: 1
y2tlab_perp: 1
y2tlab_size: 1.0

yaxis_1: !ENV '${PLOTTING_STAT_LONG} (${PLOTTING_CNT_VAR_UNITS})'
yaxis_2: ''

ylab_align: 0.5
ylab_offset: -6
ylab_size: 1
ylab_weight: 1

ylim: []

ytlab_horiz: 0.5
ytlab_orient: 1
ytlab_perp: 0.5
ytlab_size: 1

log_filename: !ENV '${PLOTTING_CNT_LOG_FILENAME}'
log_level: debug

show_legend:
- 'True'
