[config]

PROCESS_LIST = METDbLoad

MET_DB_LOAD_RUNTIME_FREQ = RUN_ONCE

LOOP_BY = VALID
VALID_TIME_FMT = %Y%m%d%H
VALID_INCREMENT = 24H

MET_DB_LOAD_INPUT_TEMPLATE = /work/output/point_stat/metplus_surface

MET_DATA_DB_DIR = /usr/local/lib/python3.14/site-packages

MET_DB_LOAD_XML_FILE = /work/config/metplus/metdbload/load_pointstat_surface.xml

MET_DB_LOAD_REMOVE_TMP_XML = True

MET_DB_LOAD_MV_HOST = mariadb:3306
MET_DB_LOAD_MV_DATABASE = mv_wrf_surface
MET_DB_LOAD_MV_USER = metuser
MET_DB_LOAD_MV_PASSWORD = 123

MET_DB_LOAD_MV_VERBOSE = false
MET_DB_LOAD_MV_INSERT_SIZE = 1
MET_DB_LOAD_MV_MODE_HEADER_DB_CHECK = false
MET_DB_LOAD_MV_DROP_INDEXES = false
MET_DB_LOAD_MV_APPLY_INDEXES = true
MET_DB_LOAD_MV_GROUP = WRF_SURFACE_IMGW
MET_DB_LOAD_MV_LOAD_STAT = true
MET_DB_LOAD_MV_LOAD_MODE = false
MET_DB_LOAD_MV_LOAD_MTD = false
MET_DB_LOAD_MV_LOAD_MPR = true
